// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/solumD/go-quotes-server/internal/model"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRepository) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRepository)(nil).Close))
}

// DeleteQuote mocks base method.
func (m *MockRepository) DeleteQuote(ctx context.Context, ID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuote", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuote indicates an expected call of DeleteQuote.
func (mr *MockRepositoryMockRecorder) DeleteQuote(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuote", reflect.TypeOf((*MockRepository)(nil).DeleteQuote), ctx, ID)
}

// GetAllQuotes mocks base method.
func (m *MockRepository) GetAllQuotes(ctx context.Context) ([]*model.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuotes", ctx)
	ret0, _ := ret[0].([]*model.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuotes indicates an expected call of GetAllQuotes.
func (mr *MockRepositoryMockRecorder) GetAllQuotes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuotes", reflect.TypeOf((*MockRepository)(nil).GetAllQuotes), ctx)
}

// GetQuotesByAuthor mocks base method.
func (m *MockRepository) GetQuotesByAuthor(ctx context.Context, quoteAuthor string) ([]*model.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotesByAuthor", ctx, quoteAuthor)
	ret0, _ := ret[0].([]*model.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotesByAuthor indicates an expected call of GetQuotesByAuthor.
func (mr *MockRepositoryMockRecorder) GetQuotesByAuthor(ctx, quoteAuthor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotesByAuthor", reflect.TypeOf((*MockRepository)(nil).GetQuotesByAuthor), ctx, quoteAuthor)
}

// GetRandomQuote mocks base method.
func (m *MockRepository) GetRandomQuote(ctx context.Context) (*model.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomQuote", ctx)
	ret0, _ := ret[0].(*model.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomQuote indicates an expected call of GetRandomQuote.
func (mr *MockRepositoryMockRecorder) GetRandomQuote(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomQuote", reflect.TypeOf((*MockRepository)(nil).GetRandomQuote), ctx)
}

// SaveQuote mocks base method.
func (m *MockRepository) SaveQuote(ctx context.Context, quoteText, quoteAuthor string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveQuote", ctx, quoteText, quoteAuthor)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveQuote indicates an expected call of SaveQuote.
func (mr *MockRepositoryMockRecorder) SaveQuote(ctx, quoteText, quoteAuthor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveQuote", reflect.TypeOf((*MockRepository)(nil).SaveQuote), ctx, quoteText, quoteAuthor)
}
